In [2]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /opt/anaconda3/envs/multi/lib/python3.7/site-packages (8.0.25)
Requirement already satisfied: protobuf>=3.0.0 in /opt/anaconda3/envs/multi/lib/python3.7/site-packages (from mysql-connector-python) (3.17.3)
Requirement already satisfied: six>=1.9 in /opt/anaconda3/envs/multi/lib/python3.7/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
#db 불러오기

import pymysql
import pandas
from sqlalchemy import create_engine
import sqlalchemy

db = pymysql.connect(
    user='root', 
    passwd='xodn8050', 
    host='localhost', 
    db='proj', 
    charset = 'utf8'
)

cursor = db.cursor(pymysql.cursors.DictCursor)

sql = "select * from `proj`.`2018skhynicx` union all SELECT * FROM `proj`.`2019skhynicx` union all select * from `proj`.`2020skhynicx`"
cursor.execute(sql)

result = cursor.fetchall()

# 데이터 프레임으로 변경
df = pandas.DataFrame(result)

In [39]:
df

,st_n,st_cd,news,date,title,url,text
0,sk하이닉스,000660,아시아경제,2018122715,"SK하이닉스, 우수 엔지니어 60세 넘어도 일할 수 있다",http://view.asiae.co.kr/news/view.htm?idxno=20...,2020년에는 상대평가제도도 폐지…소통강화 위해 호칭도 'TL'로 통일 [아시아경제...
1,sk하이닉스,000660,아시아경제,2018123110,"오션브릿지, SK하이닉스와 12억 규모 반도체 장비제조 공급계약 체결",http://view.asiae.co.kr/news/view.htm?idxno=20...,\r\t\t\t\t\t\t\t[아시아경제 오주연 기자] \r\t\t\t\t\t\t\...
2,sk하이닉스,000660,아시아경제,2018122816,"SK하이닉스, 우수 엔지니어 정년 없앤다",http://view.asiae.co.kr/news/view.htm?idxno=20...,\r\t\t\t\t\t\t\t인사제도 파격적 개편…최태원 회장의 딥체인지 실현 [아...
3,sk하이닉스,000660,아시아경제,2018122607,"[클릭 e종목]""SK하이닉스, 내년 반도체 수요 증가율 상저하고…목표가↓""",http://view.asiae.co.kr/news/view.htm?idxno=20...,\r\t\t\t\t\t\t\t[아시아경제 송화정 기자]신한금융투자는 26일 \r\t...
4,sk하이닉스,000660,아시아경제,2018122707,"[클릭 e종목]""SK하이닉스, 4Q영업익 전망치 하향""",http://view.asiae.co.kr/news/view.htm?idxno=20...,\r\t\t\t\t\t\t\t[아시아경제 오주연 기자] 하나금융투자가 27일 \r\...
...,...,...,...,...,...,...,...
5185,sk하이닉스,000660,아시아경제,2020020711,"[컨콜]SK텔레콤 ""비용 효율적 마케팅""…출혈경쟁 자제 방침 재확인",https://view.asiae.co.kr/article/2020020711535...,[아시아경제 조슬기나 기자]\r\t\t\t\t\t\t\t\tSK텔레콤SK텔레콤017...
5186,sk하이닉스,000660,아시아경제,2020020711,"[컨콜]SK텔레콤 ""지배구조 개편, 현재 구체적 방안 결정안돼""",https://view.asiae.co.kr/article/2020020711365...,[아시아경제 조슬기나 기자]\r\t\t\t\t\t\t\t\tSK텔레콤SK텔레콤017...
5187,sk하이닉스,000660,아시아경제,2020020709,"5G 출혈에…SK텔레콤 작년 영업익 1.1조, 전년비 7.6%↓(1보)",https://view.asiae.co.kr/article/2020020708301...,속보[아시아경제 조슬기나 기자] \r\t\t\t\t\t\t\t\tSK텔레콤SK텔레콤...
5188,sk하이닉스,000660,아시아경제,2020011407,"[클릭 e종목]""SK텔레콤, 여러 가지 변화 기대""",https://view.asiae.co.kr/article/2020011407401...,"NH투자증권, 투자의견 '매수'·목표주가 31만원 제시… 13일 종가 23만4500..."
5189,sk하이닉스,000660,아시아경제,2020010209,"SK이노베이션, CES서 미래 전기차 비전 'SK인사이드' 공개",https://view.asiae.co.kr/article/2020010209214...,[아시아경제 박소연 기자] SK이노베이션이 세계 최대 가전·IT 전시회인 'CES ...

In [40]:

pymysql.install_as_MySQLdb()

engine = create_engine("mysql+mysqldb://root:"+"1234"+"@3.35.70.166/proj", encoding='utf8')
conn = engine.connect()

df.to_sql(name='asia_news_craw_000660', con=engine, if_exists='append',index = False,dtype = {
'st_n':sqlalchemy.types.VARCHAR(10),
'st_cd':sqlalchemy.types.VARCHAR(10),
'news': sqlalchemy.types.TEXT(),
'n_date':sqlalchemy.types.VARCHAR(10),
'title' : sqlalchemy.types.TEXT(), 
'url' :sqlalchemy.types.TEXT(),
'text' : sqlalchemy.types.TEXT()

})

conn.close()

In [5]:
df

,st_n,st_cd,news,date,title,url,text
0,삼성전자,005930,매일경제,2019123114,삼성·LG 폰 무상수리 1년→2년…내년 1월 1일부터,http://news.mk.co.kr/newsRead.php?no=1100060&y...,\n\n\n갤럭시노트10. [사진 제공 = 삼성전자]\n 내년 1월 1일부터 스마트...
1,삼성전자,005930,매일경제,2019123116,"""44% 오른 삼성전자, 아직 저평가""…PER, 글로벌경쟁사의 절반",http://news.mk.co.kr/newsRead.php?no=1100457&y...,\n\n\n 최근 증권사들이 삼성전자 목표주가를 올리고 있다. 7만원까지 제시한 리...
2,삼성전자,005930,매일경제,2019122909,위·아래로 접는 삼성 폴더블폰 내년 2월 출시 유력,http://news.mk.co.kr/newsRead.php?no=1092814&y...,\n\n\n지난 10월 삼성개발자콘퍼런스 2019에서 소개한 클램셸 디장인 폴더블폰...
3,삼성전자,005930,매일경제,2019123106,국민연금 보유 삼성전자 지분가치 3년새 80% `급증`,http://news.mk.co.kr/newsRead.php?no=1098697&y...,\n\n\n[사진 출처=연합뉴스]\n 국민연금이 보유한 삼성전자 지분 가치가 최근 ...
4,삼성전자,005930,매일경제,2019123114,새해 ‘꿈의 화질’ 8K 시장 본격적으로 열린다… 삼성 ‘업스케일링’ 기술 vs L...,http://news.mk.co.kr/newsRead.php?no=1100102&y...,‘꿈의 화질’이 더이상 꿈이 아닌 시대가 열리고 있다. 집에서도 마치 영화관처럼 생...
...,...,...,...,...,...,...,...
2297,삼성전자,005930,매일경제,2019070200,"[사설] 한국 반도체 위기, 비상 대응체제 가동하라",http://news.mk.co.kr/newsRead.php?year=2019&no...,\n 한국 수출이 반도체를 중심으로 7개월 연속 감소했다...
2298,삼성전자,005930,매일경제,2019070117,"文대통령, 손정의 만나 `혁신 성장의 길` 모색",http://news.mk.co.kr/newsRead.php?year=2019&no...,\n\n\n 세계적 혁신 기업가인 손정의 일본 소프트뱅크 회장이 방한해 4일 청와대...
2299,삼성전자,005930,매일경제,2019070114,"[레이더M] 라온피플, IPO 본격 추진…9월 목표",http://news.mk.co.kr/newsRead.php?year=2019&no...,\n\n\n[본 기사는 06월 25일(13:45) '레이더M'에 보도 된 기사입니다...
2300,삼성전자,005930,매일경제,2019070110,트럼프도 엄지척…K-푸드 美공략 빨라진다,http://news.mk.co.kr/newsRead.php?year=2019&no...,\n\n\n도널드 트럼프 미국 대통령이 지난달 30일 그랜드 하얏트 호텔에서 열린 ...
2301,삼성전자,005930,매일경제,2019070100,[사설] 무역전쟁 불길 언제든 다시 한국 경제 덮칠 수 있다,http://news.mk.co.kr/newsRead.php?year=2019&no...,\n 일본 오사카에서 열린 G20 정상회의는 지난 29일...

In [8]:
#db 내보내기

pymysql.install_as_MySQLdb()
# engine = create_engine("mysql+mysqldb://root:"+"1234"+"@3.35.70.166/proj", encoding='utf8')
engine = create_engine("mysql+mysqldb://root:"+"1234"+"@3.35.70.166/proj", encoding='utf8')
conn = engine.connect()
    df.to_sql(name='news_craw_samsung_asia', con=engine, if_exists='append',index = False,dtype = {
    'st_n':sqlalchemy.types.VARCHAR(10),
    'st_cd':sqlalchemy.types.VARCHAR(10),
    'news': sqlalchemy.types.TEXT(),
    'n_date':sqlalchemy.types.VARCHAR(10),
    'title' : sqlalchemy.types.TEXT(), 
    'url' :sqlalchemy.types.TEXT(),
    'text' : sqlalchemy.types.TEXT()

    })

IndentationError: unexpected indent (<ipython-input-8-12f7b0258c15>, line 5)